version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${db_name}"
      MYSQL_USER: "${db_username}"
      MYSQL_PASSWORD: "${db_password}"
      MYSQL_ROOT_PASSWORD: "${db_root_password}"
    ports:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
volumes:
  my-db:
